## import dependecies

In [2]:
import pandas as pd

## get country vaccine data

In [3]:
vaccine_df = pd.read_csv('raw_csv/country_vaccinations.csv')
vaccine_df.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm...",World Health Organization,https://covid19.who.int/

## drop columns that aren't needed from vaccine data

In [3]:
vaccine_df = vaccine_df.drop(['source_name','source_website','iso_code','daily_vaccinations_raw'], axis=1)
vaccine_df.head()

,country,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines
0,Afghanistan,2021-02-22,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm..."
1,Afghanistan,2021-02-23,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm..."
2,Afghanistan,2021-02-24,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm..."
3,Afghanistan,2021-02-25,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm..."
4,Afghanistan,2021-02-26,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm..."

## isolate the most recent date

In [4]:
max_date_df = pd.DataFrame(vaccine_df.groupby('country')['date'].max())

In [5]:
cleaned_vaccine_df = pd.merge(max_date_df, vaccine_df, on = ['country', 'date'])
cleaned_vaccine_df = cleaned_vaccine_df.set_index('country')
cleaned_vaccine_df.head()

,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines
country,,,,,,,,,,
Afghanistan,2021-05-30,600152.0,480226.0,119926.0,4746.0,1.54,1.23,0.31,122.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm..."
Albania,2021-05-31,776461.0,486128.0,290333.0,7332.0,26.98,16.89,10.09,2548.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ..."
Algeria,2021-02-19,75000.0,NaN,NaN,3748.0,0.17,NaN,NaN,85.0,Sputnik V
Andorra,2021-05-17,32317.0,27613.0,4704.0,98.0,41.83,35.74,6.09,1268.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
Angola,2021-05-31,909215.0,679034.0,230181.0,12888.0,2.77,2.07,0.70,392.0,Oxford/AstraZeneca

## read in UN country data

In [4]:
un_df = pd.read_csv("raw_csv/country_profile_variables.csv")

## drop columns that aren't needed from UN country data

In [7]:
un_df = un_df.drop(['Surface area (km2)','GDP growth rate (annual %, const. 2005 prices)','Economy: Agriculture (% of GVA)','Economy: Industry (% of GVA)','Economy: Services and other activity (% of GVA)','Employment: Agriculture (% of employed)','Employment: Industry (% of employed)','Employment: Services (% of employed)','Labour force participation (female/male pop. %)','Agricultural production index (2004-2006=100)','Food production index (2004-2006=100)','International trade: Exports (million US$)','International trade: Imports (million US$)','International trade: Balance (million US$)','Balance of payments, current account (million US$)','Fertility rate, total (live births per woman)','International migrant stock (000/% of total pop.)','Refugees and others of concern to UNHCR (in thousands)','Infant mortality rate (per 1000 live births','Education: Government expenditure (% of GDP)','Education: Primary gross enrol. ratio (f/m per 100 pop.)','Education: Secondary gross enrol. ratio (f/m per 100 pop.)','Education: Tertiary gross enrol. ratio (f/m per 100 pop.)','Seats held by women in national parliaments %','Mobile-cellular subscriptions (per 100 inhabitants)','Mobile-cellular subscriptions (per 100 inhabitants).1','Individuals using the Internet (per 100 inhabitants)','Threatened species (number)','Forested area (% of land area)','CO2 emission estimates (million tons/tons per capita)','Energy production, primary (Petajoules)','Energy supply per capita (Gigajoules)','Pop. using improved drinking water (urban/rural, %)','Pop. using improved sanitation facilities (urban/rural, %)','Net Official Development Assist. received (% of GNI)'], axis=1)
un_df = un_df.set_index("country")
un_df.head()

,Region,Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),GDP per capita (current US$),Unemployment (% of labour force),Population growth rate (average annual %),Urban population (% of total population),Urban population growth rate (average annual %),"Life expectancy at birth (females/males, years)","Population age distribution (0-14 / 60+ years, %)",Health: Total expenditure (% of GDP),Health: Physicians (per 1000 pop.)
country,,,,,,,,,,,,,,
Afghanistan,SouthernAsia,35530,54.4,106.3,20270,623.2,8.6,3.2,26.7,4.0,63.5/61.0,43.2/4.1,8.2,0.3
Albania,SouthernEurope,2930,106.9,101.9,11541,3984.2,15.8,-0.1,57.4,2.2,79.9/75.6,17.4/19.0,5.9,1.3
Algeria,NorthernAfrica,41318,17.3,102.0,164779,4154.1,11.4,2.0,70.7,2.8,76.5/74.1,29.3/9.4,7.2,...
American Samoa,Polynesia,56,278.2,103.6,-99,-99.0,...,-~0.0,87.2,-0.1,77.8/71.1,33.3/9.0,-99.0,-99
Andorra,SouthernEurope,77,163.8,102.3,2812,39896.4,-99,-1.6,85.1,0.1,-99,14.4/19.0,8.1,3.7

## clean data where placeholder "-99" , ".../..." , "...", and "-~0.0"

In [17]:
un_df = un_df.replace(-99,0)
un_df = un_df.replace(".../...",0)
un_df = un_df.replace("...",0)
un_df = un_df.replace("-~0.0",0)

un_df

,Region,Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),GDP per capita (current US$),Unemployment (% of labour force),Population growth rate (average annual %),Urban population (% of total population),Urban population growth rate (average annual %),"Life expectancy at birth (females/males, years)","Population age distribution (0-14 / 60+ years, %)",Health: Total expenditure (% of GDP),Health: Physicians (per 1000 pop.)
country,,,,,,,,,,,,,,
Afghanistan,SouthernAsia,35530,54.4,106.3,20270,623.2,8.6,3.2,26.7,4.0,63.5/61.0,43.2/4.1,8.2,0.3
Albania,SouthernEurope,2930,106.9,101.9,11541,3984.2,15.8,-0.1,57.4,2.2,79.9/75.6,17.4/19.0,5.9,1.3
Algeria,NorthernAfrica,41318,17.3,102.0,164779,4154.1,11.4,2.0,70.7,2.8,76.5/74.1,29.3/9.4,7.2,0
American Samoa,Polynesia,56,278.2,103.6,0,0.0,0,0,87.2,-0.1,77.8/71.1,33.3/9.0,0.0,-99
Andorra,SouthernEurope,77,163.8,102.3,2812,39896.4,-99,-1.6,85.1,0.1,-99,14.4/19.0,8.1,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna Islands,Polynesia,12,84.1,93.4,0,0.0,-99,-2.1,0.0,0.0,78.7/72.8,25.5/15.4,0.0,-99
Western Sahara,NorthernAfrica,553,2.1,110.1,0,0.0,6.8,1.8,80.9,3.3,70.3/66.9,28.1/5.4,0.0,-99
Yemen,WesternAsia,28250,53.5,102.1,29688,1106.4,16.1,2.6,34.6,4.0,65.6/62.8,39.9/4.6,5.6,0.3
Zambia,EasternAfrica,17094,23.0,98.5,21255,1311.1,7.4,3.0,40.9,4.3,61.9/57.5,44.8/3.7,5.0,0.2
Zimbabwe,EasternAfrica,16530,42.7,95.0,13893,890.4,5.0,2.3,32.4,2.3,59.0/56.1,41.2/4.2,6.0,0.1

## get world happiness data

In [5]:
CSV_2019 = "raw_csv/2019.csv"

etl2019_df = pd.read_csv(CSV_2019)
etl2019_df

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298
...,...,...,...,...,...,...,...,...,...
151,152,Rwanda,3.334,0.359,0.711,0.614,0.555,0.217,0.411
152,153,Tanzania,3.231,0.476,0.885,0.499,0.417,0.276,0.147
153,154,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.158,0.025
154,155,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.235,0.035
155,156,South Sudan,2.853,0.306,0.575,0.295,0.010,0.202,0.091

## drop columns that aren't needed from world happiness data

In [24]:
etl2019_df = etl2019_df.drop(['Overall rank','GDP per capita'], axis = 1)
etl2019_df = etl2019_df.set_index("Country or region")

etl2019_df.head()

,Score,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
Country or region,,,,,,
Finland,7.769,1.587,0.986,0.596,0.153,0.393
Denmark,7.600,1.573,0.996,0.592,0.252,0.410
Norway,7.554,1.582,1.028,0.603,0.271,0.341
Iceland,7.494,1.624,1.026,0.591,0.354,0.118
Netherlands,7.488,1.522,0.999,0.557,0.322,0.298

## write dataframes to sql

In [11]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:1316@localhost:5432/etl_world_data', paramstyle='format')

In [26]:
cleaned_vaccine_df.to_sql('vaccine',engine, if_exists='replace')

In [27]:
un_df.to_sql('UN',engine, if_exists='replace')

In [28]:
etl2019_df.to_sql('happiness',engine, if_exists='replace')